import type { BikeListing, Offer, SavedSearch } from "@/lib/types";

const roadImage =
  "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80";
const gravelImage =
  "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=1200&q=80";
const mountainImage =
  "https://images.unsplash.com/photo-1544191696-15693072e5c9?auto=format&fit=crop&w=1200&q=80";
const workshopImage =
  "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80";
const wheelImage = "/images/wheelset.svg";

export const listings: BikeListing[] = [
  {
    id: "listing-001",
    category: "complete-bike",
    title: "2023 Specialized S-Works Tarmac SL7 Red AXS",
    model: {
      id: "model-tarmac-sl7",
      brand: "Specialized",
      modelFamily: "Tarmac",
      modelName: "S-Works Tarmac SL7",
      modelYear: 2023,
      discipline: "road",
    },
    seller: {
      id: "seller-velohouse",
      name: "Velo House Austin",
      sellerType: "shop",
      location: "Austin, TX",
      verifiedIdentity: true,
      reviewScore: 4.9,
      reviewCount: 128,
      responseRate: 0.98,
      accountAgeMonths: 43,
    },
    price: 6990,
    originalMsrp: 14000,
    dealScore: "below-market",
    frameSize: "56 cm",
    riderHeightRange: "5 ft 9 in - 6 ft 1 in",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    drivetrain: "SRAM Red AXS 2x12",
    brakes: "Hydraulic disc",
    condition: {
      overallGrade: "excellent",
      structuralFlag: "clear",
      estimatedMiles: 890,
      lastMajorService: "2026-02-18",
      serviceNotes: [
        "Brake bleed and new pads completed by shop",
        "Chain waxed at 0.25 percent wear",
        "Bottom bracket inspected with no play",
      ],
      defectTags: ["Small clear-coat mark on right chainstay"],
    },
    provenance: {
      ownershipType: "original-owner",
      proofOfPurchase: "verified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "WSBC****8241",
      theftCheckStatus: "clear",
      verificationMethod: "receipt-match",
    },
    transactionModes: ["managed-shipping", "local-pickup", "inspection-partner"],
    location: "Austin, TX",
    shipsTo: "Lower 48",
    daysOnMarket: 8,
    views: 2180,
    saves: 146,
    inquiries: 18,
    heroImage: roadImage,
    gallery: [roadImage, workshopImage, gravelImage],
  },
  {
    id: "listing-002",
    category: "complete-bike",
    title: "2022 Santa Cruz Hightower CC X01 Reserve",
    model: {
      id: "model-hightower",
      brand: "Santa Cruz",
      modelFamily: "Hightower",
      modelName: "Hightower CC X01",
      modelYear: 2022,
      discipline: "mountain",
    },
    seller: {
      id: "seller-emma",
      name: "Emma R.",
      sellerType: "private",
      location: "Boulder, CO",
      verifiedIdentity: true,
      reviewScore: 4.8,
      reviewCount: 21,
      responseRate: 0.91,
      accountAgeMonths: 29,
    },
    price: 4650,
    originalMsrp: 8499,
    dealScore: "fair",
    frameSize: "Large",
    riderHeightRange: "5 ft 10 in - 6 ft 2 in",
    wheelSize: "29 in",
    frameMaterial: "Carbon",
    drivetrain: "SRAM X01 Eagle",
    brakes: "SRAM Code RSC",
    suspension: "150 mm front / 145 mm rear",
    condition: {
      overallGrade: "very-good",
      structuralFlag: "clear",
      estimatedMiles: 1240,
      lastMajorService: "2026-03-04",
      serviceNotes: [
        "Fork lower service completed in March",
        "New Maxxis Assegai front tire",
        "Rear shock air-can service documented",
      ],
      defectTags: ["Shoe rub on non-drive crank", "Cosmetic shuttle pad mark"],
    },
    provenance: {
      ownershipType: "second-owner",
      proofOfPurchase: "pending",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "pending",
      maskedSerial: "PS21****5520",
      theftCheckStatus: "pending",
      verificationMethod: "seller-entry",
    },
    transactionModes: ["local-pickup", "managed-shipping"],
    location: "Boulder, CO",
    shipsTo: "Continental US",
    daysOnMarket: 14,
    views: 1640,
    saves: 88,
    inquiries: 11,
    heroImage: mountainImage,
    gallery: [mountainImage, workshopImage, roadImage],
  },
  {
    id: "listing-003",
    category: "complete-bike",
    title: "2024 Cervelo Aspero Force AXS Gravel",
    model: {
      id: "model-aspero",
      brand: "Cervelo",
      modelFamily: "Aspero",
      modelName: "Aspero Force AXS",
      modelYear: 2024,
      discipline: "gravel",
    },
    seller: {
      id: "seller-chainline",
      name: "Chainline Consignment",
      sellerType: "consignment",
      location: "Bentonville, AR",
      verifiedIdentity: true,
      reviewScore: 4.7,
      reviewCount: 63,
      responseRate: 0.94,
      accountAgeMonths: 18,
    },
    price: 3850,
    originalMsrp: 6200,
    dealScore: "below-market",
    frameSize: "54 cm",
    riderHeightRange: "5 ft 7 in - 5 ft 11 in",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    drivetrain: "SRAM Force AXS XPLR",
    brakes: "Hydraulic disc",
    condition: {
      overallGrade: "excellent",
      structuralFlag: "clear",
      estimatedMiles: 510,
      lastMajorService: "2026-01-26",
      serviceNotes: [
        "New bar tape and brake pads",
        "Tubeless sealant refreshed",
        "Firmware updated on derailleur and shifters",
      ],
      defectTags: ["Light fork-leg scuff from bag rub"],
    },
    provenance: {
      ownershipType: "original-owner",
      proofOfPurchase: "verified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "SN24****0183",
      theftCheckStatus: "clear",
      verificationMethod: "inspection-partner",
    },
    transactionModes: ["managed-shipping", "inspection-partner"],
    location: "Bentonville, AR",
    shipsTo: "Lower 48",
    daysOnMarket: 3,
    views: 1940,
    saves: 122,
    inquiries: 21,
    heroImage: gravelImage,
    gallery: [gravelImage, roadImage, workshopImage],
  },
  {
    id: "listing-004",
    category: "complete-bike",
    title: "2021 Trek Fuel EX 9.8 XT Project One",
    model: {
      id: "model-fuel-ex",
      brand: "Trek",
      modelFamily: "Fuel EX",
      modelName: "Fuel EX 9.8 XT",
      modelYear: 2021,
      discipline: "mountain",
    },
    seller: {
      id: "seller-drew",
      name: "Drew M.",
      sellerType: "private",
      location: "Asheville, NC",
      verifiedIdentity: true,
      reviewScore: 4.6,
      reviewCount: 12,
      responseRate: 0.87,
      accountAgeMonths: 15,
    },
    price: 3290,
    originalMsrp: 6499,
    dealScore: "fair",
    frameSize: "Medium/Large",
    riderHeightRange: "5 ft 7 in - 5 ft 11 in",
    wheelSize: "29 in",
    frameMaterial: "Carbon",
    drivetrain: "Shimano XT 12-speed",
    brakes: "Shimano XT 4-piston",
    suspension: "140 mm front / 130 mm rear",
    condition: {
      overallGrade: "good",
      structuralFlag: "clear",
      estimatedMiles: 1860,
      lastMajorService: "2025-12-11",
      serviceNotes: [
        "Fresh chain and cassette",
        "Suspension service records uploaded",
        "Pivot bearings checked in December",
      ],
      defectTags: ["Paint chips on downtube guard", "Rear rim has one small ding"],
    },
    provenance: {
      ownershipType: "second-owner",
      proofOfPurchase: "pending",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "pending",
      maskedSerial: "WTU****3916",
      theftCheckStatus: "clear",
      verificationMethod: "seller-entry",
    },
    transactionModes: ["local-pickup"],
    location: "Asheville, NC",
    daysOnMarket: 25,
    views: 960,
    saves: 54,
    inquiries: 6,
    heroImage: mountainImage,
    gallery: [mountainImage, gravelImage, workshopImage],
  },
  {
    id: "listing-005",
    category: "complete-bike",
    title: "2023 Canyon Grail CF SLX Di2",
    model: {
      id: "model-grail",
      brand: "Canyon",
      modelFamily: "Grail",
      modelName: "Grail CF SLX Di2",
      modelYear: 2023,
      discipline: "gravel",
    },
    seller: {
      id: "seller-pedalroom",
      name: "Pedal Room Certified",
      sellerType: "certified-partner",
      location: "Minneapolis, MN",
      verifiedIdentity: true,
      reviewScore: 5,
      reviewCount: 44,
      responseRate: 0.99,
      accountAgeMonths: 34,
    },
    price: 3550,
    originalMsrp: 5799,
    dealScore: "below-market",
    frameSize: "Small",
    riderHeightRange: "5 ft 4 in - 5 ft 8 in",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    drivetrain: "Shimano GRX Di2",
    brakes: "Hydraulic disc",
    condition: {
      overallGrade: "excellent",
      structuralFlag: "clear",
      estimatedMiles: 440,
      lastMajorService: "2026-03-15",
      serviceNotes: [
        "Certified inspection completed",
        "New chain installed",
        "Tubeless setup refreshed",
      ],
      defectTags: ["Minor crank arm shoe polish"],
    },
    provenance: {
      ownershipType: "demo",
      proofOfPurchase: "verified",
      commercialUse: true,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "R089****7042",
      theftCheckStatus: "clear",
      verificationMethod: "inspection-partner",
    },
    transactionModes: ["managed-shipping", "inspection-partner", "local-pickup"],
    location: "Minneapolis, MN",
    shipsTo: "Lower 48",
    daysOnMarket: 5,
    views: 1314,
    saves: 91,
    inquiries: 14,
    heroImage: gravelImage,
    gallery: [gravelImage, workshopImage, wheelImage],
  },
  {
    id: "listing-006",
    category: "complete-bike",
    title: "2020 Cannondale SuperSix EVO Hi-MOD",
    model: {
      id: "model-supersix",
      brand: "Cannondale",
      modelFamily: "SuperSix EVO",
      modelName: "Hi-MOD Disc Ultegra",
      modelYear: 2020,
      discipline: "road",
    },
    seller: {
      id: "seller-luis",
      name: "Luis V.",
      sellerType: "private",
      location: "San Diego, CA",
      verifiedIdentity: true,
      reviewScore: 4.9,
      reviewCount: 17,
      responseRate: 0.95,
      accountAgeMonths: 24,
    },
    price: 2750,
    originalMsrp: 7250,
    dealScore: "below-market",
    frameSize: "58 cm",
    riderHeightRange: "6 ft 0 in - 6 ft 3 in",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    drivetrain: "Shimano Ultegra mechanical",
    brakes: "Hydraulic disc",
    condition: {
      overallGrade: "very-good",
      structuralFlag: "clear",
      estimatedMiles: 2600,
      lastMajorService: "2025-11-06",
      serviceNotes: [
        "New cables and housing",
        "Rotors measured within spec",
        "Chain at 0.4 percent wear",
      ],
      defectTags: ["Two paint nicks near rear dropout"],
    },
    provenance: {
      ownershipType: "original-owner",
      proofOfPurchase: "verified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "CAAD****6719",
      theftCheckStatus: "clear",
      verificationMethod: "receipt-match",
    },
    transactionModes: ["local-pickup", "managed-shipping"],
    location: "San Diego, CA",
    shipsTo: "Continental US",
    daysOnMarket: 31,
    views: 1042,
    saves: 77,
    inquiries: 9,
    heroImage: roadImage,
    gallery: [roadImage, gravelImage, workshopImage],
  },
  {
    id: "listing-007",
    category: "complete-bike",
    title: "2024 Orbea Wild M-Team eMTB",
    model: {
      id: "model-wild",
      brand: "Orbea",
      modelFamily: "Wild",
      modelName: "Wild M-Team",
      modelYear: 2024,
      discipline: "e-bike",
    },
    seller: {
      id: "seller-peakcycles",
      name: "Peak Cycles Denver",
      sellerType: "shop",
      location: "Denver, CO",
      verifiedIdentity: true,
      reviewScore: 4.8,
      reviewCount: 204,
      responseRate: 0.96,
      accountAgeMonths: 61,
    },
    price: 7790,
    originalMsrp: 10999,
    dealScore: "fair",
    frameSize: "Large",
    riderHeightRange: "5 ft 10 in - 6 ft 2 in",
    wheelSize: "29 in",
    frameMaterial: "Carbon",
    drivetrain: "Shimano XT",
    brakes: "Shimano XT 4-piston",
    suspension: "170 mm front / 160 mm rear",
    condition: {
      overallGrade: "excellent",
      structuralFlag: "clear",
      estimatedMiles: 310,
      lastMajorService: "2026-02-28",
      serviceNotes: [
        "Battery health report at 98 percent",
        "Bosch diagnostic report uploaded",
        "Full bolt check and brake bleed",
      ],
      defectTags: ["Light scuff on left chainstay protector"],
    },
    provenance: {
      ownershipType: "demo",
      proofOfPurchase: "verified",
      commercialUse: true,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "ORB****2240",
      theftCheckStatus: "clear",
      verificationMethod: "inspection-partner",
    },
    transactionModes: ["local-pickup", "inspection-partner"],
    location: "Denver, CO",
    daysOnMarket: 11,
    views: 1705,
    saves: 118,
    inquiries: 16,
    heroImage: mountainImage,
    gallery: [mountainImage, workshopImage, roadImage],
  },
  {
    id: "listing-008",
    category: "complete-bike",
    title: "2022 Giant Propel Advanced Pro 0",
    model: {
      id: "model-propel",
      brand: "Giant",
      modelFamily: "Propel",
      modelName: "Advanced Pro 0",
      modelYear: 2022,
      discipline: "road",
    },
    seller: {
      id: "seller-tri-cave",
      name: "Tri Cave Resale",
      sellerType: "consignment",
      location: "Scottsdale, AZ",
      verifiedIdentity: true,
      reviewScore: 4.7,
      reviewCount: 39,
      responseRate: 0.9,
      accountAgeMonths: 21,
    },
    price: 3150,
    originalMsrp: 6700,
    dealScore: "fair",
    frameSize: "Medium",
    riderHeightRange: "5 ft 7 in - 5 ft 11 in",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    drivetrain: "Shimano Ultegra Di2",
    brakes: "Hydraulic disc",
    condition: {
      overallGrade: "very-good",
      structuralFlag: "inspection-recommended",
      estimatedMiles: 1450,
      lastMajorService: "2025-10-19",
      serviceNotes: [
        "Di2 battery replaced",
        "Fresh tires and bar tape",
        "Inspection recommended due to race use disclosure",
      ],
      defectTags: ["Race number sticker ghosting", "Small bar-end scrape"],
    },
    provenance: {
      ownershipType: "race",
      proofOfPurchase: "pending",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "pending",
      maskedSerial: "GIA****1187",
      theftCheckStatus: "pending",
      verificationMethod: "seller-entry",
    },
    transactionModes: ["managed-shipping", "local-pickup"],
    location: "Scottsdale, AZ",
    shipsTo: "Lower 48",
    daysOnMarket: 19,
    views: 880,
    saves: 42,
    inquiries: 5,
    heroImage: roadImage,
    gallery: [roadImage, wheelImage, workshopImage],
  },
  {
    id: "listing-009",
    category: "frame",
    title: "2023 Yeti SB140 Turq Frame",
    model: {
      id: "model-sb140",
      brand: "Yeti",
      modelFamily: "SB140",
      modelName: "Turq Frame",
      modelYear: 2023,
      discipline: "mountain",
    },
    seller: {
      id: "seller-peakcycles",
      name: "Peak Cycles Denver",
      sellerType: "shop",
      location: "Denver, CO",
      verifiedIdentity: true,
      reviewScore: 4.8,
      reviewCount: 204,
      responseRate: 0.96,
      accountAgeMonths: 61,
    },
    price: 2490,
    originalMsrp: 4300,
    dealScore: "fair",
    frameSize: "Medium",
    riderHeightRange: "5 ft 6 in - 5 ft 10 in",
    wheelSize: "29 in",
    frameMaterial: "Carbon",
    suspension: "140 mm rear",
    condition: {
      overallGrade: "excellent",
      structuralFlag: "clear",
      estimatedMiles: 300,
      lastMajorService: "2026-03-02",
      serviceNotes: ["Switch Infinity serviced", "Frame bearings checked"],
      defectTags: ["Tiny cable rub mark under head tube"],
    },
    provenance: {
      ownershipType: "shop-owned",
      proofOfPurchase: "verified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "YET****9021",
      theftCheckStatus: "clear",
      verificationMethod: "inspection-partner",
    },
    transactionModes: ["managed-shipping", "inspection-partner", "local-pickup"],
    location: "Denver, CO",
    shipsTo: "Lower 48",
    daysOnMarket: 6,
    views: 760,
    saves: 49,
    inquiries: 7,
    heroImage: mountainImage,
    gallery: [mountainImage, workshopImage, gravelImage],
  },
  {
    id: "listing-010",
    category: "frame",
    title: "2022 Enve Melee Frameset 54",
    model: {
      id: "model-melee",
      brand: "Enve",
      modelFamily: "Melee",
      modelName: "Frameset",
      modelYear: 2022,
      discipline: "road",
    },
    seller: {
      id: "seller-maya",
      name: "Maya S.",
      sellerType: "private",
      location: "Portland, OR",
      verifiedIdentity: true,
      reviewScore: 4.9,
      reviewCount: 33,
      responseRate: 0.92,
      accountAgeMonths: 37,
    },
    price: 2100,
    originalMsrp: 5500,
    dealScore: "below-market",
    frameSize: "54 cm",
    riderHeightRange: "5 ft 7 in - 5 ft 11 in",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    condition: {
      overallGrade: "very-good",
      structuralFlag: "clear",
      estimatedMiles: 980,
      lastMajorService: "2025-09-12",
      serviceNotes: ["Headset bearings replaced", "No carbon damage found"],
      defectTags: ["Paint chip near front derailleur mount"],
    },
    provenance: {
      ownershipType: "original-owner",
      proofOfPurchase: "verified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "ENV****6128",
      theftCheckStatus: "clear",
      verificationMethod: "receipt-match",
    },
    transactionModes: ["managed-shipping", "local-pickup"],
    location: "Portland, OR",
    shipsTo: "Lower 48",
    daysOnMarket: 17,
    views: 690,
    saves: 55,
    inquiries: 8,
    heroImage: roadImage,
    gallery: [roadImage, workshopImage, wheelImage],
  },
  {
    id: "listing-011",
    category: "frame",
    title: "2021 Ibis Hakka MX Frameset",
    model: {
      id: "model-hakka",
      brand: "Ibis",
      modelFamily: "Hakka",
      modelName: "MX Frameset",
      modelYear: 2021,
      discipline: "gravel",
    },
    seller: {
      id: "seller-summit",
      name: "Summit Used Cycles",
      sellerType: "shop",
      location: "Salt Lake City, UT",
      verifiedIdentity: true,
      reviewScore: 4.6,
      reviewCount: 74,
      responseRate: 0.88,
      accountAgeMonths: 50,
    },
    price: 1290,
    originalMsrp: 3299,
    dealScore: "below-market",
    frameSize: "55 cm",
    riderHeightRange: "5 ft 8 in - 6 ft 0 in",
    wheelSize: "700c / 650b",
    frameMaterial: "Carbon",
    condition: {
      overallGrade: "good",
      structuralFlag: "clear",
      estimatedMiles: 2200,
      lastMajorService: "2025-08-08",
      serviceNotes: ["Threaded bottom bracket chased", "Fork steerer inspected"],
      defectTags: ["Bag rub on top tube", "Heel rub on both stays"],
    },
    provenance: {
      ownershipType: "second-owner",
      proofOfPurchase: "unverified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "unverified",
      maskedSerial: "IBS****0000",
      theftCheckStatus: "not-checked",
      verificationMethod: "seller-entry",
    },
    transactionModes: ["local-pickup", "managed-shipping"],
    location: "Salt Lake City, UT",
    shipsTo: "Continental US",
    daysOnMarket: 44,
    views: 412,
    saves: 24,
    inquiries: 3,
    heroImage: gravelImage,
    gallery: [gravelImage, workshopImage, roadImage],
  },
  {
    id: "listing-012",
    category: "wheelset",
    title: "Zipp 353 NSW Tubeless Disc Wheelset",
    model: {
      id: "model-zipp-353",
      brand: "Zipp",
      modelFamily: "353 NSW",
      modelName: "Tubeless Disc Wheelset",
      modelYear: 2024,
      discipline: "road",
    },
    seller: {
      id: "seller-velohouse",
      name: "Velo House Austin",
      sellerType: "shop",
      location: "Austin, TX",
      verifiedIdentity: true,
      reviewScore: 4.9,
      reviewCount: 128,
      responseRate: 0.98,
      accountAgeMonths: 43,
    },
    price: 2250,
    originalMsrp: 4220,
    dealScore: "below-market",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    brakes: "Centerlock disc",
    condition: {
      overallGrade: "excellent",
      structuralFlag: "clear",
      estimatedMiles: 380,
      lastMajorService: "2026-02-12",
      serviceNotes: ["Bearings smooth", "Fresh tubeless tape installed"],
      defectTags: ["Tiny decal scuff on rear rim"],
    },
    provenance: {
      ownershipType: "shop-owned",
      proofOfPurchase: "verified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "ZIP****4922",
      theftCheckStatus: "clear",
      verificationMethod: "receipt-match",
    },
    transactionModes: ["managed-shipping", "local-pickup"],
    location: "Austin, TX",
    shipsTo: "Lower 48",
    daysOnMarket: 9,
    views: 590,
    saves: 62,
    inquiries: 10,
    heroImage: wheelImage,
    gallery: [wheelImage, roadImage, workshopImage],
  },
  {
    id: "listing-013",
    category: "wheelset",
    title: "Reserve 30 SL Carbon 29 Wheelset",
    model: {
      id: "model-reserve-30",
      brand: "Reserve",
      modelFamily: "30 SL",
      modelName: "Carbon 29 Wheelset",
      modelYear: 2023,
      discipline: "mountain",
    },
    seller: {
      id: "seller-emma",
      name: "Emma R.",
      sellerType: "private",
      location: "Boulder, CO",
      verifiedIdentity: true,
      reviewScore: 4.8,
      reviewCount: 21,
      responseRate: 0.91,
      accountAgeMonths: 29,
    },
    price: 1180,
    originalMsrp: 2199,
    dealScore: "fair",
    wheelSize: "29 in",
    frameMaterial: "Carbon",
    brakes: "6-bolt disc",
    condition: {
      overallGrade: "very-good",
      structuralFlag: "clear",
      estimatedMiles: 650,
      lastMajorService: "2025-12-29",
      serviceNotes: ["Rear hub serviced", "Spokes tensioned by shop"],
      defectTags: ["One cosmetic rock strike on front rim"],
    },
    provenance: {
      ownershipType: "original-owner",
      proofOfPurchase: "verified",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "verified",
      maskedSerial: "RSV****8820",
      theftCheckStatus: "clear",
      verificationMethod: "receipt-match",
    },
    transactionModes: ["local-pickup", "managed-shipping"],
    location: "Boulder, CO",
    shipsTo: "Continental US",
    daysOnMarket: 13,
    views: 420,
    saves: 37,
    inquiries: 4,
    heroImage: wheelImage,
    gallery: [wheelImage, mountainImage, workshopImage],
  },
  {
    id: "listing-014",
    category: "wheelset",
    title: "Enve G23 Gravel Wheelset",
    model: {
      id: "model-g23",
      brand: "Enve",
      modelFamily: "G23",
      modelName: "Gravel Wheelset",
      modelYear: 2022,
      discipline: "gravel",
    },
    seller: {
      id: "seller-chainline",
      name: "Chainline Consignment",
      sellerType: "consignment",
      location: "Bentonville, AR",
      verifiedIdentity: true,
      reviewScore: 4.7,
      reviewCount: 63,
      responseRate: 0.94,
      accountAgeMonths: 18,
    },
    price: 1390,
    originalMsrp: 2550,
    dealScore: "fair",
    wheelSize: "700c",
    frameMaterial: "Carbon",
    brakes: "Centerlock disc",
    condition: {
      overallGrade: "good",
      structuralFlag: "clear",
      estimatedMiles: 1700,
      lastMajorService: "2025-11-20",
      serviceNotes: ["New tubeless valves", "Freehub cleaned and greased"],
      defectTags: ["Decal wear", "Cassette bite marks on freehub body"],
    },
    provenance: {
      ownershipType: "second-owner",
      proofOfPurchase: "pending",
      commercialUse: false,
      accidentDisclosed: false,
    },
    serial: {
      state: "pending",
      maskedSerial: "ENV****3055",
      theftCheckStatus: "pending",
      verificationMethod: "seller-entry",
    },
    transactionModes: ["managed-shipping", "local-pickup"],
    location: "Bentonville, AR",
    shipsTo: "Lower 48",
    daysOnMarket: 22,
    views: 380,
    saves: 29,
    inquiries: 3,
    heroImage: wheelImage,
    gallery: [wheelImage, gravelImage, workshopImage],
  },
];

export const offers: Offer[] = [
  {
    id: "offer-001",
    listingId: "listing-001",
    buyerName: "Jordan K.",
    amount: 6650,
    status: "countered",
    lastMessage:
      "I can do pickup this weekend if the serial verification stays clear.",
  },
  {
    id: "offer-002",
    listingId: "listing-003",
    buyerName: "Nina P.",
    amount: 3700,
    status: "open",
    lastMessage: "Would you include the second wheelset rotors?",
  },
  {
    id: "offer-003",
    listingId: "listing-007",
    buyerName: "Caleb M.",
    amount: 7400,
    status: "accepted",
    lastMessage: "Accepted pending inspection-partner pickup window.",
  },
];

export const savedSearches: SavedSearch[] = [
  {
    id: "saved-001",
    name: "Verified gravel bikes 54-56",
    filters: {
      discipline: "gravel",
      category: "complete-bike",
      verifiedSerial: true,
      maxPrice: 4500,
    },
    resultCount: 3,
    alertFrequency: "instant",
  },
  {
    id: "saved-002",
    name: "Large trail bikes with shipping",
    filters: {
      discipline: "mountain",
      frameSize: "Large",
      transactionMode: "managed-shipping",
    },
    resultCount: 2,
    alertFrequency: "daily",
  },
  {
    id: "saved-003",
    name: "Carbon road wheels under 2500",
    filters: {
      category: "wheelset",
      discipline: "road",
      maxPrice: 2500,
    },
    resultCount: 1,
    alertFrequency: "weekly",
  },
];

export function getListing(id: string) {
  return listings.find((listing) => listing.id === id);
}

export const featuredListings = listings
  .filter((listing) => listing.serial.state === "verified")
  .slice(0, 6);

export const newestListings = [...listings].sort(
  (a, b) => a.daysOnMarket - b.daysOnMarket,
);
